version: "3.8"

services:

    bitcoin-core:
        container_name: bitcoin-core
        build: .
        volumes:
            - "./data-local:/media/bitcoin"
        ports:
            - "127.0.0.1:8332-8333:8332-8333"
